### ISSUE TITLE
Bug when sorting yaml with double quotes

### ISSUE THREAD

**Issue by Lyczeq** [ddebin/yaml-sort#5]
**Description**

Sometimes when I use the yaml-sort command with pre-commit it messes up two lines that are double-quoted.

In the screen below you can see a composition of the yaml file I have.
![image](https://user-images.githubusercontent.com/56163767/153404351-95fc38c0-1ea9-4def-bd26-630846e5f1b0.png)

The `k8s-name-input` key has a value that starts and ends with double quotes but also includes single quotes in the middle.

When I edit the value of the `hide` key from `Hide read-only fields` to e.g. `Hide all fields` and then use `git add` and `git commit...` commands, the value of the `k8s-name-input` messes up to:

![image](https://user-images.githubusercontent.com/56163767/153405330-52c79625-d0a5-49c0-8a04-1cbf33655f38.png)

As you can see, the the `k8s-name-input` value is single-quoted and includes more single-quotes inside.

It happens from time to time, there are situations when it doesn't break the `k8s-name-input`.

The yaml-sort command I use:
`yaml-sort --lineWidth=-1  -i`

**Comment by ddebin** [comment]
AFAIK changing the quoting style (from double to single quote) doesn't break the YAML. [`js-yaml`](https://github.com/nodeca/js-yaml#dump-object---options-) (used by `yaml-sort`) default to single-quoting style but I think I can add an option to force double-quoting style instead.
