### ISSUE TITLE
support stdin

### ISSUE THREAD

**Issue by hauntingEcho** [ddebin/yaml-sort#6]
due to NodeJS [lacking support for process substitution in some environments](https://github.com/nodejs/node/issues/18255), sending data directly to yaml-sort via something like `yaml-sort -i <(echo "test:stuff") -s` is not always currently possible (and does not work for me in Windows).  Adding support to read from stdin would make this much more useful in scripts, allowing it to be used in pipelines, e.g. `cat original.yaml | yq ".paths./customers.get.parameters" | grep -v "^\s*x-position" | yaml-sort` to return a sorted list of parameters for an endpoint in an OpenAPI file after removing NSwag's x-position extension property.

**Comment by ddebin** [comment]
@hauntingEcho Please see #8 if it suits your need.
